### ISSUE TITLE
Kernel panic running testsuite

### ISSUE THREAD

**Issue by andypugh** [NTULINUX/RTAI#14]
Jepler has been running tests not involving LinuxCNC, so I am suspecting this is a different issue:
https://gist.github.com/jepler/212d2093f7feb22232f6d2a432e9cacd

**Comment by NTULINUX** [comment]
RTAI doesn't work in QEMU, Xenomai does.

**Comment by NTULINUX** [comment]
4.14 has been dropped for quite some time, please test with a later kernel on bare metal and re-open if issue persists.
